// Generated from the two authoritative screenplay PDFs.
export const screenplayCat = [
  "L'ÚLTIM CLAU\nGuió literari - Versió catalana\nCurtmetratge / Cortometraje - Durada aproximada / Duración\naproximada: 3'30''\nGuió i direcció / Guion y dirección\nENRIKE SEGARRA\nSetembre / Septiembre 2026",
  "INT. AMAGATALL SOTA UN GRANER - NIT\nSEGONA GUERRA MUNDIAL. SUD DE FRANÇA.\nUn espai estret, fosc i gairebé abstracte sota una trapa del graner.\nNormalment s'utilitza per guardar-hi restes de menjar per als animals.\nMARC i LAIA, d'entre vint-i-sis i trenta anys, són republicans catalans\nexiliats després de la Guerra Civil. Fa dies que viuen amagats en aquell\nforat. Marc parla valencià. Laia parla català.\nLa pantalla encara és negra.\nCORTINETA OFICIAL DEL FESTIVAL\nMentre veiem la cortineta, comencem a escoltar el so de l'escena.\nUn moviment lleu sobre la fusta.\nLa roba que es mou amb cura.\nLa respiració continguda de dues persones que intenten no fer soroll.\nMarc s'acosta a Laia.\nUn PETÓ breu, inesperat.\nLa cortineta arriba al final.\nLa imatge de l'escena apareix sense interrompre el so.\nUna entrada mínima de llum retalla fragments dels seus cossos. Rostres,\nmans i pell emergeixen de la foscor com en un quadre de Caravaggio.\nMarc té els llavis sobre el coll de Laia.\nLaia tanca els ulls durant un instant. Li agrada, però intenta\ncontenir-se.\nLi posa una mà al pit.\nNo l'aparta completament.\nLAIA\n(entre murmuris)\nMarc... què fas? Estàs boig?\nMARC\nNomés un poc.\nMarc intenta besar-la als llavis.\nLaia gira lleugerament el rostre i evita el petó, però continua aferrada a\nla seva camisa.\nLAIA\nAra no.\nMarc s'atura immediatament.\nNo insisteix físicament.\nLa mira, encara molt a prop d'ella.\nMARC\nFa dies que no venen.\nLaia dirigeix una mirada cap a la trapa.\nEscolta.\nNo se sent res.\nMarc comença a apartar-se.\nPerò Laia no deixa anar la seva camisa.\nQuan ell intenta retirar-se, ella l'atura i l'apropa lleugerament.\nMarc entén el gest.\nS'acosta una altra vegada i li besa el coll. Després, l'espatlla.\nLaia tanca els ulls.",
  "Deixa escapar l'aire involuntàriament. Els seus dits s'aferren amb més\nforça a la camisa de Marc.\nLi agrada, però la por continua present.\nMarc continua baixant lentament pel seu cos, besant-la amb suavitat.\nLaia obre els ulls i el mira. En la seva mirada hi ha una advertència,\nperò també tendresa i un gest juganer.\nLAIA\nMarc...\nMarc no s'atura.\nContinua baixant a poc a poc, mantenint la seva mirada durant un instant.\nLa paraula no és un rebuig. És una crida íntima, plena d'afecte i de desig\ncontingut.\nSilenci.\nTots dos es miren amb afecte.\nQuan arriba a la seva intimitat, Laia li agafa la mà amb força.\nNo per apartar-lo.\nPer retenir-lo.\nMarc entén el gest.\nLi practica sexe oral.\nLaia intenta contenir la respiració.\nVol dir alguna cosa.\nNomés aconsegueix xiuxiuejar:\nLAIA\nEns sentiran...\nPerò no l'aparta.\nLa frase es perd entre la seva respiració.\nLaia tanca els ulls i es deixa portar, conscient del que està passant.\nLes seves mans continuen subjectant Marc.\nEll segueix.\nLa tensió entre tots dos augmenta.\nFinalment, Laia l'apropa cap a ella i el besa.\nLAIA\nNomés una estona.\nMARC\nNomés una estona.\nEs besen.\nAra sí, tots dos.\nEls seus cossos es busquen amb delicadesa, procurant no fer cap soroll.\nFragments entre llums i ombres:\nUns LLAVIS.\nUna MÀ recorrent una esquena.\nEls DITS de Laia aferrats a la camisa de Marc.\nLa FUSTA cedint lleugerament sota el pes dels seus cossos.\nEs miren amb amor i amb una melangia que cap dels dos no s'atreveix a\nanomenar.\nDe sobte:\nPASSOS a l'exterior.\nMarc i Laia s'aturen.\nVeus de SOLDATS parlant en alemany.",
  "La porta del graner s'obre.\nCORONEL NAZI (OFF)\n(en alemany; subtitulat en català)\nFragen Sie ihn, was da unten ist.\n(Pregunteu-li què hi ha allà baix.)\nSERGENT NAZI (OFF)\n(en anglès; subtitulat en català, al\ngranger)\nWhat is down there?\n(Què hi ha allà baix?)\nGRANGER (OFF)\n(en anglès, amb accent francès;\nsubtitulat en català)\nNothing. Only scraps of food for the animals.\nYour men searched it a few weeks ago.\n(Res. Només restes de menjar per als animals.\nEls seus homes ja ho van escorcollar fa unes\nsetmanes.)\nEl sergent tradueix la resposta a l'alemany.\nMarc i Laia romanen completament immòbils.\nLaia comença a respirar massa de pressa.\nMarc li tapa suaument la boca amb una mà.\nMARC\n(molt fluix)\nMira'm.\nLaia fixa els ulls en ell.\nIntenta controlar l'atac de pànic.\nSobre els seus caps, el coronel camina lentament pel graner.\nCada passa fa caure una mica de pols damunt d'ells.\nCORONEL NAZI (OFF)\n(en alemany; subtitulat en català)\nDurchsuchen Sie es noch einmal.\n(Escorcolleu-ho una altra vegada.)\nSERGENT NAZI (OFF)\n(en alemany, als soldats; subtitulat en\ncatalà)\nNoch einmal durchsuchen.\n(Torneu-ho a escorcollar.)\nEls soldats obeeixen.\nEls PASSOS comencen a acostar-se.\nLAIA\nVenen cap aquí.\nMARC\nTranquil·la. No passarà res.\nLAIA\nObriran la trapa.\nMARC\nLaia...\nLaia l'agafa de la camisa i l'apropa cap a ella.\nMARC\nQuè fas? Estàs boja?\nLaia el mira.",
  "Té por, però també una estranya serenitat.\nLAIA\nSi ens troben...\nUna passa ressona just damunt d'ells.\nLAIA\n...que ens troben vivint.\nDurant un instant, cap dels dos no es mou.\nDesprés es besen.\nJa no hi ha delicadesa ni contenció.\nFan l'amor amb desesperació, amb ràbia, amb la necessitat d'aferrar-se a\nla vida durant uns segons més.\nEls PASSOS s'apropen mentre el moviment dels seus cossos es torna cada\nvegada més intens.\nMANS buscant pell.\nDITS enfonsant-se en una esquena.\nRESPIRACIONS accelerades.\nLa FUSTA cruix sota els seus cossos.\nUn soldat s'atura just damunt d'ells.\nSOLDAT NAZI (OFF)\n(en alemany; subtitulat en català)\nHier.\n(Aquí.)\nUna mà colpeja la trapa des de l'exterior.\nMarc i Laia ho senten.\nNo s'aturen.\nLa trapa comença a obrir-se.\nUna entrada violenta de llum blanca cau sobre els seus cossos\nentrellaçats.\nLes siluetes dels soldats apareixen damunt d'ells.\nMarc i Laia no miren cap amunt.\nContinuen fent l'amor.\nMés de pressa.\nAmb més intensitat.\nNomés es miren l'un a l'altre.\nEls soldats alcen les armes.\nLes respiracions de Marc i Laia arriben al límit.\nLa fusta cruix.\nEls dits s'aferren.\nEls seus cossos arriben al clímax.\nAL MATEIX INSTANT:\nUna RÀFEGA DE TRETS.\nUna LLUM BLANCA, intensa i violenta, devora completament la imatge.\nTALL A BLANC.\nLa respiració de tots dos s'apaga entre els últims trets.\nSilenci.\nMantenim el blanc durant uns segons.",
  "Sobre el blanc:\nL'ÚLTIM CLAU\nFI."
] as const;

export const screenplayEs = [
  "L'ÚLTIM CLAU\nGuion literario - Versión castellana para el equipo técnico\nCurtmetratge / Cortometraje - Durada aproximada / Duración\naproximada: 3'30''\nGuió i direcció / Guion y dirección\nENRIKE SEGARRA\nSetembre / Septiembre 2026",
  "INT. ESCONDITE BAJO UN GRANERO - NOCHE\nSEGUNDA GUERRA MUNDIAL. SUR DE FRANCIA.\nUn espacio estrecho, oscuro y casi abstracto bajo una trampilla del\ngranero. Normalmente se utiliza para almacenar restos de comida para los\nanimales.\nMARC y LAIA, de entre veintiséis y treinta años, son republicanos\ncatalanes exiliados tras la Guerra Civil. Llevan días viviendo escondidos\nen aquel agujero. Marc habla valenciano. Laia habla catalán.\nLa pantalla todavía está negra.\nCORTINILLA OFICIAL DEL FESTIVAL\nMientras vemos la cortinilla, comenzamos a escuchar el sonido de la\nescena.\nUn movimiento leve sobre la madera.\nLa ropa moviéndose con cuidado.\nLa respiración contenida de dos personas que intentan no hacer ruido.\nMarc se acerca a Laia.\nUn BESO breve, inesperado.\nLa cortinilla llega a su fin.\nLa imagen de la escena aparece sin interrumpir el sonido.\nUna entrada mínima de luz recorta fragmentos de sus cuerpos. Rostros,\nmanos y piel emergen de la oscuridad como en un cuadro de Caravaggio.\nMarc tiene los labios sobre el cuello de Laia.\nLaia cierra los ojos durante un instante. Le gusta, pero intenta\ncontenerse.\nLe pone una mano en el pecho.\nNo lo aparta completamente.\nLAIA\n(entre susurros)\nMarc... ¿qué haces? ¿Estás loco?\nMARC\nSolo un poco.\nMarc intenta besarla en los labios.\nLaia gira ligeramente el rostro y evita el beso, pero continúa aferrada a\nsu camisa.\nLAIA\nAhora no.\nMarc se detiene inmediatamente.\nNo insiste físicamente.\nLa mira, todavía muy cerca de ella.\nMARC\nLlevan días sin venir.\nLaia dirige una mirada hacia la trampilla.\nEscucha.\nNo se oye nada.\nMarc comienza a apartarse.\nPero Laia no suelta su camisa.\nCuando él intenta retirarse, ella lo detiene y lo acerca ligeramente.\nMarc entiende el gesto.\nSe aproxima de nuevo y le besa el cuello. Después, el hombro.\nLaia cierra los ojos.",
  "Deja escapar el aire involuntariamente. Sus dedos se aferran con más\nfuerza a la camisa de Marc.\nLe gusta, pero el miedo continúa presente.\nMarc continúa bajando lentamente por su cuerpo, besándola con suavidad.\nLaia abre los ojos y lo mira. En su mirada hay una advertencia, pero\ntambién ternura y un gesto juguetón.\nLAIA\nMarc...\nMarc no se detiene.\nContinúa bajando poco a poco, manteniendo su mirada durante un instante.\nLa palabra no es un rechazo. Es una llamada íntima, llena de afecto y\ndeseo contenido.\nSilencio.\nLos dos se miran con cariño.\nCuando llega a su intimidad, Laia le agarra la mano con fuerza.\nNo para apartarlo.\nPara retenerlo.\nMarc entiende el gesto.\nLe practica sexo oral.\nLaia intenta contener la respiración.\nQuiere decir algo.\nSolo consigue susurrar:\nLAIA\nNos oirán...\nPero no lo aparta.\nLa frase se pierde entre su respiración.\nLaia cierra los ojos y se deja llevar, consciente de lo que está\nocurriendo.\nSus manos continúan sujetando a Marc.\nÉl continúa.\nLa tensión entre ambos aumenta.\nFinalmente, Laia lo acerca hacia ella y lo besa.\nLAIA\nSolo un rato.\nMARC\nSolo un rato.\nSe besan.\nAhora sí, los dos.\nSus cuerpos se buscan con delicadeza, procurando no hacer ningún ruido.\nFragmentos entre luces y sombras:\nUnos LABIOS.\nUna MANO recorriendo una espalda.\nLos DEDOS de Laia aferrados a la camisa de Marc.\nLa MADERA cediendo ligeramente bajo el peso de sus cuerpos.\nSe miran con amor y con una melancolía que ninguno de los dos se atreve a\nnombrar.\nDe pronto:\nPASOS en el exterior.\nMarc y Laia se detienen.",
  "Voces de SOLDADOS hablando en alemán.\nLa puerta del granero se abre.\nCORONEL NAZI (OFF)\n(en alemán; subtitulado en castellano)\nFragen Sie ihn, was da unten ist.\n(Pregúntele qué hay ahí abajo.)\nSARGENTO NAZI (OFF)\n(en inglés; subtitulado en castellano, al\ngranjero)\nWhat is down there?\n(¿Qué hay ahí abajo?)\nGRANJERO (OFF)\n(en inglés, con acento francés;\nsubtitulado en castellano)\nNothing. Only scraps of food for the animals.\nYour men searched it a few weeks ago.\n(Nada. Solo restos de comida para los animales.\nSus hombres ya lo registraron hace unas\nsemanas.)\nEl sargento traduce la respuesta al alemán.\nMarc y Laia permanecen completamente inmóviles.\nLaia comienza a respirar demasiado deprisa.\nMarc le tapa suavemente la boca con una mano.\nMARC\n(muy bajo)\nMírame.\nLaia fija los ojos en él.\nIntenta controlar el ataque de pánico.\nSobre sus cabezas, el coronel camina lentamente por el granero.\nCada paso hace caer un poco de polvo sobre ellos.\nCORONEL NAZI (OFF)\n(en alemán; subtitulado en castellano)\nDurchsuchen Sie es noch einmal.\n(Regístrenlo otra vez.)\nSARGENTO NAZI (OFF)\n(en alemán, a los soldados; subtitulado\nen castellano)\nNoch einmal durchsuchen.\n(Registradlo otra vez.)\nLos soldados obedecen.\nLos PASOS comienzan a acercarse.\nLAIA\nVienen hacia aquí.\nMARC\nTranquila. No va a pasar nada.\nLAIA\nAbrirán la trampilla.\nMARC\nLaia...\nLaia lo agarra de la camisa y lo acerca hacia ella.\nMARC\n¿Qué haces? ¿Estás loca?",
  "Laia lo mira.\nTiene miedo, pero también una extraña serenidad.\nLAIA\nSi nos encuentran...\nUn paso resuena justo encima de ellos.\nLAIA\n...que nos encuentren viviendo.\nDurante un instante, ninguno de los dos se mueve.\nDespués se besan.\nYa no hay delicadeza ni contención.\nHacen el amor con desesperación, con rabia, con la necesidad de aferrarse\na la vida durante unos segundos más.\nLos PASOS se aproximan mientras el movimiento de sus cuerpos se vuelve\ncada vez más intenso.\nMANOS buscando piel.\nDEDOS hundiéndose en una espalda.\nRESPIRACIONES aceleradas.\nLa MADERA cruje bajo sus cuerpos.\nUn soldado se detiene justo encima de ellos.\nSOLDADO NAZI (OFF)\n(en alemán; subtitulado en castellano)\nHier.\n(Aquí.)\nUna mano golpea la trampilla desde el exterior.\nMarc y Laia lo oyen.\nNo se detienen.\nLa trampilla comienza a abrirse.\nUna entrada violenta de luz blanca cae sobre sus cuerpos entrelazados.\nLas siluetas de los soldados aparecen sobre ellos.\nMarc y Laia no miran hacia arriba.\nContinúan haciendo el amor.\nMás deprisa.\nCon mayor intensidad.\nSolo se miran el uno al otro.\nLos soldados levantan las armas.\nLas respiraciones de Marc y Laia llegan al límite.\nLa madera cruje.\nLos dedos se aferran.\nSus cuerpos alcanzan el clímax.\nAL MISMO TIEMPO:\nUna RÁFAGA DE DISPAROS.\nUna LUZ BLANCA, intensa y violenta, devora completamente la imagen.\nCORTE A BLANCO.\nLa respiración de ambos se apaga entre los últimos disparos.\nSilencio.\nMantenemos el blanco durante unos segundos.",
  "Sobre el blanco:\nL'ÚLTIM CLAU\nFIN."
] as const;

export type ScriptLineRole = 'character' | 'parenthetical' | 'dialogue';
type ScriptPageRoles = Readonly<Record<number, ScriptLineRole>>;

// These annotations preserve the literal PDF-derived text while making its
// cinematic structure explicit. Every line not listed here is an action.
export const screenplayRoles: Record<'cat' | 'es', readonly ScriptPageRoles[]> = {
  cat: [
    {},
    { 24: 'character', 25: 'parenthetical', 26: 'dialogue', 27: 'character', 28: 'dialogue', 32: 'character', 33: 'dialogue', 37: 'character', 38: 'dialogue' },
    { 6: 'character', 7: 'dialogue', 22: 'character', 23: 'dialogue', 31: 'character', 32: 'dialogue', 33: 'character', 34: 'dialogue' },
    { 1: 'character', 2: 'parenthetical', 3: 'dialogue', 4: 'parenthetical', 5: 'character', 6: 'parenthetical', 7: 'parenthetical', 8: 'dialogue', 9: 'parenthetical', 10: 'character', 11: 'parenthetical', 12: 'parenthetical', 13: 'dialogue', 14: 'dialogue', 15: 'parenthetical', 16: 'parenthetical', 17: 'parenthetical', 22: 'character', 23: 'parenthetical', 24: 'dialogue', 29: 'character', 30: 'parenthetical', 31: 'dialogue', 32: 'parenthetical', 33: 'character', 34: 'parenthetical', 35: 'parenthetical', 36: 'dialogue', 37: 'parenthetical', 40: 'character', 41: 'dialogue', 42: 'character', 43: 'dialogue', 44: 'character', 45: 'dialogue', 46: 'character', 47: 'dialogue', 49: 'character', 50: 'dialogue' },
    { 1: 'character', 2: 'dialogue', 4: 'character', 5: 'dialogue', 18: 'character', 19: 'parenthetical', 20: 'dialogue', 21: 'parenthetical' },
    {},
  ],
  es: [
    {},
    { 26: 'character', 27: 'parenthetical', 28: 'dialogue', 29: 'character', 30: 'dialogue', 34: 'character', 35: 'dialogue', 39: 'character', 40: 'dialogue' },
    { 6: 'character', 7: 'dialogue', 22: 'character', 23: 'dialogue', 32: 'character', 33: 'dialogue', 34: 'character', 35: 'dialogue' },
    { 2: 'character', 3: 'parenthetical', 4: 'dialogue', 5: 'parenthetical', 6: 'character', 7: 'parenthetical', 8: 'parenthetical', 9: 'dialogue', 10: 'parenthetical', 11: 'character', 12: 'parenthetical', 13: 'parenthetical', 14: 'dialogue', 15: 'dialogue', 16: 'parenthetical', 17: 'parenthetical', 18: 'parenthetical', 23: 'character', 24: 'parenthetical', 25: 'dialogue', 30: 'character', 31: 'parenthetical', 32: 'dialogue', 33: 'parenthetical', 34: 'character', 35: 'parenthetical', 36: 'parenthetical', 37: 'dialogue', 38: 'parenthetical', 41: 'character', 42: 'dialogue', 43: 'character', 44: 'dialogue', 45: 'character', 46: 'dialogue', 47: 'character', 48: 'dialogue', 50: 'character', 51: 'dialogue' },
    { 2: 'character', 3: 'dialogue', 5: 'character', 6: 'dialogue', 19: 'character', 20: 'parenthetical', 21: 'dialogue', 22: 'parenthetical' },
    {},
  ],
};
